# Workflow for linting, building, testing, CodeQL analysis, and reporting of code coverage

name: Node.js CI

on:
  push:
    branches: [main]
#    paths:
#      - 'src/**'
#      - 'tests/**'
#      - '.github/workflows/ci-push.yml'
#  schedule:
#    - cron: '0 5 * * 1'
  workflow_dispatch:

jobs:
  upload_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Copy to Toolforge
        uses: appleboy/scp-action@9ba62064d28ce0897a970e72cdfe30b9fde2fe48
        with:
          source: ${{github.workspace}}/LocalSettings.php
          strip_components: 2
          target: /data/project/mwn/www
          host: login.toolforge.org
          username: ${{secrets.TOOLFORGE_USERNAME}}
          key: ${{secrets.TOOLFORGE_PRIVATE_KEY}}

