# Workflow for linting, building, testing, CodeQL analysis, and reporting of code coverage

name: Node.js CI

on:
  push:
    branches: [main]
#    paths:
#      - 'src/**'
#      - 'tests/**'
#      - '.github/workflows/ci-push.yml'
#  schedule:
#    - cron: '0 5 * * 1'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git branch | cat
        env:
          KEY: ${{ secrets.TOOLFORGE_PRIVATE_KEY }}
