name: 'deploy'
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Run build and ensure tests are passing before deployment
      - run: npm run --if-present build
      - run: npm run --if-present test
      - name: Deploy to Wikipedia
        uses: wikimedia-gadgets/deploy-action@v1
        with:
          paths: 'src/myscript.js User:SDZeroBot/deploy-test.js'
          apiUrl: 'https://test.wikipedia.org/w/api.php'

          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
