name: Docs deploy

on:
  push:
    branches: [ 'main' ]
  release:
    types: [ 'created' ]
  workflow_dispatch:

jobs:
  versiondocs:
    runs-on: ubuntu-latest
    steps:
      - run: "echo $EVENT"
        env:
          EVENT: ${{github.event_name}}
