name: Docs deploy

on:
  push:
    branches: [ 'master' ]
  release:
    types: [ 'created' ]
  workflow_dispatch:

jobs:
  versiondocs:
    runs-on: ubuntu-latest
    if: ${{github.event_name}} == 'release'
    steps:
      - run: echo "Hello World"
