# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: npm i

      - name: MediaWiki Docker image
        run: >-
          docker run --name=mediawiki_wiki
          -p 8080:8080
          -e MEDIAWIKI_SERVER=http://localhost:8080
          -e MEDIAWIKI_SITENAME=MyWiki
          -e MEDIAWIKI_LANGUAGE_CODE=en
          -e MEDIAWIKI_DB_TYPE=sqlite
          -e MEDIAWIKI_DB_NAME=wikidb
          -e MEDIAWIKI_ENABLE_UPLOADS=1
          -v /var/mediawiki/images:/images
          -v /var/mediawiki/data:/data
          -d kristophjunge/mediawiki

      - name: Setup MediaWiki
        run: |
          docker exec mediawiki_wiki /script/install.sh wikiuser wikipassword

      - name: Test MediaWiki API endpoint
        run: |
          curl 'localhost:8080/api.php?action=query&format=json&titles=A' --compressed


