name: Fallbacks update

on:
  schedule:
    - cron: '* * 1 * *' # monthly
  workflow_dispatch:
  push: 

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git clone --depth 1 --branch master https://github.com/wikimedia/mediawiki
          cd mediawiki/languages/messages
          echo -e "{\n$(grep '$fallback ' * | grep -v txt | sed 's/^Messages/"/' | sed 's/.php:$fallback =/": [/' | sed 's/;/ ],/' | sed 's/, /", "/g' | sed "s/'/\"/g" | sed 's/_/-/' | tr '[:upper:]' '[:lower:]' | sed "s/\/\/.*//" | sed 's/^/  /')\n}" > ../../../actions-testing/fallbacks.json
          cd ../../../actions-testing
          git config --local user.email "actions_bot@github.com"
          git config --local user.name "actions_bot"
          git add fallbacks.json
          git commit -m "Update fallbacks"
          cat fallbacks.json
      - name: Push changes
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          branch: main

      
