name: Fallbacks update

on:
  schedule:
    - cron: '* * 1 * *' # monthly
  workflow_dispatch:
  push: # REMOVEME

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: echo env var
        run: echo $GITHUB_WORKSPACE
      - name: Update npm packages
        uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            npm install
            node fallbacks-update.js
          COMMIT_MESSAGE: 'Update fallback languages'
          COMMIT_NAME: 'Banana-i18n bot'
          COMMIT_EMAIL: 'banana-i18n-bot@github.com'
          PR_BRANCH_NAME: 'fallbacks-update-${PR_ID}'
          PR_TITLE: 'Update fallback languages'
