name: Fallbacks update

on:
  schedule:
    - cron: '* * 1 * *' # monthly
  workflow_dispatch:
  push: 

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: wikimedia/mediawiki
      - run: cd mediawiki/languages/messages
      - run: |
          echo "{\n$(grep '$fallback ' * | grep -v txt | sed 's/^Messages/"/' | sed 's/.php:$fallback =/": [/' | sed 's/;/ ],/' | sed 's/, /", "/g' | sed "s/'/\"/g" | sed 's/_/-/' | tr '[:upper:]' '[:lower:]' | sed "s/\/\/.*//" | sed 's/^/  /')\n}" > fallbacks.json
          git config --local user.email "bot@github.com"
          git config --local user.name "bot"
          git commit -am "Update fallbacks"

      
