# Preserve the build output of every successful build from pushes and PRs on Toolforge

name: Test

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p ~/.ssh
          echo -e "$GERRIT_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          mkdir twinkle-core
          cd twinkle-core
          git init
          git remote add gerrit "ssh://$GERRIT_USER@gerrit.wikimedia.org:29418/mediawiki/gadgets/TwinkleCore"
          git pull gerrit i18n
          rm -rf ~/.ssh
        env:
          GERRIT_USER: ${{secrets.GERRIT_USER}}
          GERRIT_KEY: ${{secrets.GERRIT_KEY}}

          
