# Preserve the build output of every successful build from pushes and PRs on Toolforge

name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.pusher.name == 'siddharthvp' }}
    steps:
      - run: echo Hello World

    
    
    
    
#       - uses: actions/checkout@v2
#       - name: Read package.json version
#         uses: martinbeentjes/npm-get-version-action@master
#         id: get-version
#       - run: 'echo $VERSION'
#         env: 
#           VERSION: ${{ steps.get-version.outputs.current-version }}
#       - name: Save the documentation with version number
#         uses: garygrossgarten/github-action-ssh@2b10f41b5a33808f6d24eafd253296766308b7c4
#         with:
#           command: >-
#             export VN=$VERSION;
#             become twinkle bash -c '
#               cd /data/project/twinkle/www/static;
#               cp -r core-docs "core-docs-test-$VN";
#               cd /data/project/twinkle/public_html;
#               cp -r core-docs "core-docs-test-$VN";
#             '
#           host: login.toolforge.org
#           username: ${{ secrets.TOOLFORGE_USERNAME }}
#           privateKey: ${{ secrets.TOOLFORGE_PRIVATE_KEY }}
#         env:
#           VERSION: ${{ steps.get-version.outputs.current-version }}
