name: Docs deploy

on:
  push:
    branches: [ 'main' ]
  release:
    types: [ 'created' ]
  workflow_dispatch:

jobs:
  versiondocs:
    runs-on: ubuntu-latest
    if: ${{ ${{github.event_name}} == 'release' }}
    steps:
      - uses: actions/checkout@v2
      - name: Read package.json version
        uses: martinbeentjes/npm-get-version-action@master
        id: get-version
      - run: echo "$VERSION"
        env: 
          VERSION: ${{ steps.get-version.outputs.current-version }}
      - run: echo ${{github.event_name}}
